name: Deploy to EC2

# Run code on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Copy code to server using SCP
    - name: Copy code to EC2
      env:
        SSH_AUTH_SOCK: /tmp/ssh_auth_sock
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.ssh_key }}"
        cp -r $GITHUB_WORKSPACE/* /tmp/workspace
        scp -r -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i <(echo "${{ secrets.ssh_key }}") /tmp/workspace/* ubuntu@18.222.145.229:/home/ubuntu

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 18.222.145.229  # Add your EC2 instance public IP/domain
        username: ubuntu  # EC2 username
        key: ${{ secrets.ssh_key }}  # SSH private key stored as secret
        script: |
          cd /home/ubuntu
          ls
          sudo apt-get install nginx
          sudo service nginx stop
          # Run any additional deployment steps here
