name: Deploy to EC2

#run code on new bush to main branch
on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 18.222.145.229  # Add your EC2 instance public IP/domain
        username: ubuntu  # EC2 username
        key: ${{ secrets.ssh_key }}  # SSH private key stored as secret
        script: |
          cd /home/ubuntu
          sudo apt-get install nginx
          sudo service nginx stop
          ls 
          scp -r hello.py ubuntu@18.222.145.229:/home/ubuntu

          # Run Python script
          cd /home/ubuntu
          python3 hello.py
