name: Deploy to EC2

# Run code on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # List files in the current directory
    - name: List files in current directory
      run: ls -la

    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: python
        remote: home/ubuntu
        host: 18.222.145.229
        port: 22
        username: ubuntu
        privateKey: ${{secrets.ssh_key}}

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 18.222.145.229  # Add your EC2 instance public IP/domain
        username: ubuntu  # EC2 username
        key: ${{ secrets.ssh_key }}  # SSH private key stored as secret
        script: |
          cd /home/ubuntu
          ls
          sudo apt-get install nginx
          sudo service nginx stop
          # Run any additional deployment steps here
